jdk: openjdk11
language: java
jobs:
  include:
    - stage: "Testing"
      name: "Running e2e tests"
      script:
        - "./mvnw clean test"
    - stage: deploy
      name: "Deployment"
      script: skip
      deploy: &heroku
        provider: heroku
        app: borosr-spring-boot-app
        api_key: $HEROKU_AUTH_TOKEN