jdk: openjdk11
language: java
jobs:
  include:
    - stage: "Testing"
      name: "Running e2e tests"
      script:
        - "./mvnw clean test"
    - stage: deploy
      name: "Deployment"
      script:
        - "echo 'Deployment starting...'"